[build-system]
requires = ["setuptools>=61", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "deepmd-pytorch"
dynamic = ["version"]
description = "Implementation of DeepMD-kit using PyTorch"
authors = [
  {name = "DP Technology"},
]
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3.7",
    "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)",
]
dependencies = [
     'tensorflow==2.10.0',
     'deepmd-kit==2.1.5',
     'torch',
]
requires-python = ">=3.7"
readme = "README.md"
keywords = ["DeepMD-kit", "pytorch"]

[tool.setuptools.packages.find]
include = ["deepmd_pt*"]

[tool.setuptools_scm]
write_to = "deepmd_pt/_version.py"
