name: Build docker image and push to Docker Hub

on:
  push:
    tags:
      - '*'

jobs:
  build-n-push:
    name: Build docker image and push to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Log in to Docker Registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: dp-harbor-registry.us-east-1.cr.aliyuncs.com
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: |
          dp-harbor-registry.us-east-1.cr.aliyuncs.com/eflops/deepmd-pytorch

    - name: Build and push Docker images
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Sync image
      run: >-
        wget https://dlc-cli.oss-cn-zhangjiakou.aliyuncs.com/light/binary/linux/amd64/dlc &&
        chmod +x dlc &&
        ./dlc config --access_id ${{ secrets.DLC_ACCESS_ID }} --endpoint ${{ secrets.DLC_ENDPOINT }} --access_key ${{ secrets.DLC_ACCESS_KEY }} --protocol http &&
        for i in '${{ steps.meta.outputs.tags }}'; do
          ./dlc sync-image --image_tag ${i##*/};
        done

    - name: send email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.feishu.cn
        server_port: 465
        username: ${{ secrets.MAILUSERNAME }}
        password: ${{ secrets.MAILPASSWORD }}
        subject: Docker Auto Build for DeePMD-Pytorch
        body: |
          Docker image has been pushed to ${{ steps.meta.outputs.tags }}
        to: ${{ secrets.MAIL_RECEIVER_LIST }}
        from: Github Actions
        content_type: text
