name: Run unittests

on:
  - push
  - pull_request

jobs:
  build:
    runs-on:
      group: Default

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.10
      uses: actions/setup-python@master
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install -e .
        pip install -r tests/requirements.txt
    - name: Test
      run: DEVICE=cpu PREPROCESS_DEVICE=cpu DISABLE_TQDM=True coverage run --source=./deepmd_pt -m unittest -v -f && coverage report
    - uses: codecov/codecov-action@v3
